---
version: '3.6'

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  build:
    context: config/goquorum
    args:
      QUORUM_VERSION: ${QUORUM_VERSION:-22.7.1}
  expose:
    - 30303
    - 8545
    - 9545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s

x-tessera-def:
  &tessera-def
  build:
    context: config/tessera
    args:
      TESSERA_VERSION: ${TESSERA_VERSION:-22.1.7}
  environment:
    TESSERA_MODE: tessera
  expose:
    - 9000
    - 9080
    - 9101
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:9000/upcheck"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s

x-blockscout-ref:
  &blockscout-def
  image: consensys/blockscout:v4.1.5-beta
  container_name: blockscout
  restart: "no"
  environment:
    - PORT=4000
    - ECTO_USE_SSL=false
    - DATABASE_URL=postgresql://postgres:postgres@blockscoutpostgres:5432/postgres?ssl=false
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - NETWORK=quickstart
    - NETWORK=Dev Quickstart
    - SUBNETWORK=Quorum
    - CHAIN_ID=1337
    - COIN=ETH
    - ETHEREUM_JSONRPC_VARIANT=geth
    - ETHEREUM_JSONRPC_TRANSPORT=http
    - ETHEREUM_JSONRPC_HTTP_URL=http://rpcnode:8547
    - ETHEREUM_JSONRPC_TRACE_URL=http://rpcnode:8547
    - ETHEREUM_JSONRPC_WS_URL=ws://rpcnode:8548
  entrypoint:
    - /bin/sh
    - -c
    - |
      cd /opt/app/;
      echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
  depends_on:
    - blockscoutpostgres
  links:
    - blockscoutpostgres
  ports:
    - 26000:4000

x-blockscoutpostgres-ref:
  &blockscoutpostgres-def
  image: postgres:13.6-alpine
  restart: "on-failure"
  container_name: blockscoutpostgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST_AUTH_METHOD=trust
  volumes:
    - blockscoutpostgres:/var/lib/postgresql/data
  ports:
    - 5432
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 5s
    timeout: 10s
    retries: 5




services:
  rpcnode:
    << : *quorum-def
    container_name: rpcnode
    ports:
      - 8547:8545/tcp
      - 8548:8546/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=qbft
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/rpcnode:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-network:
        ipv4_address: 172.16.239.15

  tessera1:
    << : *tessera-def
    container_name: tessera1
    ports:
      - 9081:9080
    volumes:
      - ./config/nodes/member1:/config/keys
    networks:
      quorum-network:
        ipv4_address: 172.16.239.26

  member1:
    << : *quorum-def
    container_name: member1
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 30303
      - 9545
    depends_on:
      - tessera1
    environment:
      - QUORUM_PTM=tessera1
    volumes:
      - ./config/nodes/member1:/config/keys
    networks:
      quorum-network:
        ipv4_address: 172.16.239.16

  tessera2:
    << : *tessera-def
    container_name: tessera2
    ports:
      - 9082:9080
    volumes:
      - ./config/nodes/member2:/config/keys
    networks:
      quorum-network:
        ipv4_address: 172.16.239.27

  member2:
    << : *quorum-def
    container_name: member2
    ports:
      - '20002:8545/tcp'
      - '20003:8546/tcp'
      - '30303'
      - '9545'
    depends_on:
      - tessera2
    environment:
      - QUORUM_PTM=tessera2
    volumes:
      - ./config/nodes/member2:/config/keys
    networks:
      quorum-network:
        ipv4_address: 172.16.239.17

  explorer:
    image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
    container_name: quorum-blockexplorer
    volumes:
      - ./quorum-explorer/config.json:/app/config.json
      - ./quorum-explorer/env:/app/.env.production
    depends_on:
      - rpcnode
    ports:
      - 25000:25000/tcp
    networks:
      quorum-network:
        ipv4_address: 172.16.239.31

  blockscout:
    << : *blockscout-def
    networks:
      quorum-network:
        ipv4_address: 172.16.239.51

  blockscoutpostgres:
    << : *blockscoutpostgres-def
    networks:
      quorum-network:
        ipv4_address: 172.16.239.52


networks:
  quorum-network:
    name: quorum-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

volumes:
  blockscoutpostgres: